name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Checkstyle (Gradle)
        run: ./gradlew checkstyleMain
        working-directory: /home/runner/work/Automatization_Java/Automatization_Java/Practice5_E_CommerceAppWithTesting
