name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Show root
        run: ls -l
      
      - name: Show Automatization_Java
        run: ls -l Automatization_Java
