name: Java CI/CD Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

      
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3.14.1
        with:
          distribution: 'microsoft'
          java-version: '21'

      - name: Make gradlew executable
        run: chmod +x gradlew
        working-directory: ./Practice5_E_CommerceAppWithTesting

      - name: Build JAR
        run: ./gradlew shadowJar
        working-directory: ./Practice5_E_CommerceAppWithTesting

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: ecommerse-jar
          path: ./Practice5_E_CommerceAppWithTesting/Frontend/build/libs/*.jar

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download JAR from previous job
        uses: actions/download-artifact@v4
        with:
          name: ecommerse-jar

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            Automatically created release ${{ github.ref_name }}

      - name: List downloaded files
        run: ls -l

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./
          asset_name: E-CommerseApp.jar
          asset_content_type: application/java-archive
